#!/bin/bash
KUBERNETES_USERSETUP_HOME=/home/${KUBERNETES_USERSETUP_USER}
mkdir -p ${KUBERNETES_USERSETUP_HOME}/.kube
cp -i /etc/kubernetes/admin.conf ${KUBERNETES_USERSETUP_HOME}/.kube/config
chown -R ${KUBERNETES_USERSETUP_USER}:${KUBERNETES_USERSETUP_USER} ${KUBERNETES_USERSETUP_HOME}/.kube
